pipeline {
    agent any

    tools { 
        maven 'maven'
        jdk 'java-17'
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Branch: ${env.BRANCH_NAME}"
                git url: 'https://github.com/rashmi-murthi/student-crud-minimal.git',
                    branch: "${env.BRANCH_NAME}",
                    credentialsId: 'github'
            }
        }

        stage('Compile') {
            steps { sh 'mvn compile' }
        }

        stage('Build JAR') {
            steps { sh 'mvn package -DskipTests' }
        }

        stage('Docker Build') {
            steps { sh 'docker build -t rashmimurthi/student-app:${BUILD_NUMBER}-main .' }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push rashmimurthi/student-app:${BUILD_NUMBER}-main
                    '''
                }
            }
        }

        stage('Deploy (MAIN only)') {
            steps {
                sh '''
                    docker stop student-app || true
                    docker rm student-app || true
                    docker run -d -p 8081:8080 --name student-app rashmimurthi/student-app:${BUILD_NUMBER}-main
                '''
            }
        }

    }
}

