pipeline {
    agent any

    tools {
        maven 'maven'
        jdk 'java-17'
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Branch: ${env.BRANCH_NAME}"
                git url: 'https://github.com/rashmi-murthi/student-crud-minimal.git',
                    branch: "${env.BRANCH_NAME}",
                    credentialsId: 'github'
            }
        }

        stage('Compile') {
            steps { sh 'mvn compile' }
        }

        stage('Build JAR') {
            steps { sh 'mvn package -DskipTests' }
        }

    }
}

